### ISSUE TITLE
Writing ExifDateTime fails with an assertion error

### ISSUE THREAD

**Issue by plampila** [photostructure/exiftool-vendored.js#50] opened 2019-06-16 12:54 UTC
**Describe the bug**
Writing ExifDateTime fails with an assertion error.

```
{ AssertionError [ERR_ASSERTION]: cannot encode {"year":2019,"month":1,"day":1,"hour":0,"minute":0,"second":0}
    at enc (...\node_modules\exiftool-vendored\dist\WriteTask.js:73:36)
...
```

**To Reproduce**
```javascript
const exiftool = require("exiftool-vendored").exiftool;
const ExifDateTime = require("exiftool-vendored").ExifDateTime;

test().catch(e => { console.error(e); });

async function test() {
    try {
        await exiftool.write('test.jpg', {
            CreateDate: new ExifDateTime(2019, 1, 1, 0, 0, 0),
        });
    } finally {
        await exiftool.end();
    }
}
```

**Environment (please complete the following information):**
exiftool-vendored v8.12.0
node v10.10.0
Windows 10

**Comment by mceachen** [comment] 2019-06-16 13:24
This is by design. Use `ExifDate` if you don't have time.

**Comment by plampila** [comment] 2019-06-16 13:40
I have set the time, but it still fails.

It fails even if I use ExifDate.

If it's intended to fail, it surely should not fail with an assertion error.

When using TypeScript it is not possible to use ExifDate or string without forcing it to ignore type check.

**Comment by mceachen** [comment] 2019-06-16 13:53
> When using TypeScript it is not possible to use ExifDate or string without forcing it to ignore type check.

Agreed, that should be fixed.

**Comment by mceachen** [comment] 2019-06-16 18:27
Note that `CreateDate` must be a datetime, not just a date:

```sh
 $ exiftool -CreateDate=2019:01:01 test.jpg
Warning: Invalid date/time (use YYYY:mm:dd HH:MM:SS[.ss][+/-HH:MM|Z]) in ExifIFD:CreateDate (PrintConvInv)
```

**Comment by mceachen** [comment] 2019-06-17 04:13
Better write tag support was implemented in the newest release.

**Closed by mceachen** 2019-06-17 04:13 UTC

**Comment by plampila** [comment] 2019-06-18 18:25
Works like a charm now, much appreciated!
