### ISSUE TITLE
GPS Date/Time - epoch 0 throws exception

### ISSUE THREAD

**Issue by EmmEm** [photostructure/exiftool-vendored.js#118] opened 2022-11-01 12:14 UTC
**Describe the bug**
When reading exif data from an image with GPS Date/Time set to 1970:01:01 00:00:00Z an exception is thrown. 

![image](https://user-images.githubusercontent.com/6670818/199229129-6f510cd4-9172-4b74-abbd-e32fb4d1cacd.png)

Se image:
![image](https://user-images.githubusercontent.com/6670818/199229002-1482485f-8b8a-4003-bbdb-6e419c4eb0af.png)

**To Reproduce**
Grab a jpg and add the date 1970:01:01 00:00:00Z to GPS Date/Time

```
exiftool "-GPSTimeStamp=1970:01:01 00:00:00Z" "-GPSDateStamp=1970:01:01 00:00:00Z" example.jpeg
```

Try and read exif data from the image.

If needed I can provide a jpg

**Expected behavior**
The exif data should be parsed and returned

**Environment (please complete the following information):**
 - OS and version: osx 12.4
 - Node.JS version: v16.15.0

Thanks for a very useful and fast lib!

**Comment by mceachen** [comment] 2022-11-01 20:05
I can't reproduce your error. Can you please add a failing test?

BTW: that's an invalid `GPSTimeStamp`:  those are only supposed to be `HH:MM:SS.sss`. See https://exiftool.org/TagNames/GPS.html

**Comment by mceachen** [comment] 2022-11-02 16:25
I'm going to close this, as I believe 797fa62 addresses your error. If it doesn't, please comment and I'll reopen this issue.

Thanks for taking the time to report!

**Closed by mceachen** 2022-11-02 16:25 UTC

**Comment by EmmEm** [comment] 2022-11-02 18:02
This solved my problem, thanks for a fast fix!! 🎉
